### ISSUE TITLE
Build on node.js 8.1.4 fails

### ISSUE THREAD

**Issue by softwarecreations** [bayleeadamoss/zazu#298]
### Steps to reproduce the behavior
git clone git@github.com:tinytacoteam/zazu.git
cd zazu
npm install
npm run release
open releases

### Versions

* Zazu: master
* OS: ubuntu 16.04

It seems to break at `cc1plus: warning:`

```
bob@pc:/tmp/del/zazu-master$ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> robotjs@0.4.7 install /tmp/del/zazu-master/node_modules/robotjs
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.0
prebuild-install info looking for local prebuild @ prebuilds/robotjs-v0.4.7-node-v57-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/dev/.npm/_prebuilds/https-github.com-octalmage-robotjs-releases-download-v0.4.7-robotjs-v0.4.7-node-v57-linux-x64.tar.gz
prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-linux-x64.tar.gz
prebuild-install http 404 https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.1.4 runtime=node arch=x64 platform=linux)
make: Entering directory '/tmp/del/zazu-master/node_modules/robotjs/build'
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
cc1plus: warning: command line option ‘-Wbad-function-cast’ is valid for C/ObjC but not for C++
In file included from ../src/keypress.h:6:0,
                 from ../src/robotjs.cc:7:
../src/keycode.h:103:23: fatal error: X11/Xutil.h: No such file or directory
compilation terminated.
robotjs.target.mk:114: recipe for target 'Release/obj.target/robotjs/src/robotjs.o' failed
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
make: Leaving directory '/tmp/del/zazu-master/node_modules/robotjs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dev/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.8.0-36-generic
gyp ERR! command "/home/dev/.nvm/versions/node/v8.1.4/bin/node" "/home/dev/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/del/zazu-master/node_modules/robotjs
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN @0.5.2 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2017-07-12T06_00_47_696Z-debug.log
bob@pc:/tmp/del/zazu-master$ npm run release

> @0.5.2 prerelease /tmp/del/zazu-master
> npm install


> robotjs@0.4.7 install /tmp/del/zazu-master/node_modules/robotjs
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.0
prebuild-install info looking for local prebuild @ prebuilds/robotjs-v0.4.7-node-v57-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/dev/.npm/_prebuilds/https-github.com-octalmage-robotjs-releases-download-v0.4.7-robotjs-v0.4.7-node-v57-linux-x64.tar.gz
prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-linux-x64.tar.gz
prebuild-install http 404 https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.1.4 runtime=node arch=x64 platform=linux)
make: Entering directory '/tmp/del/zazu-master/node_modules/robotjs/build'
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
cc1plus: warning: command line option ‘-Wbad-function-cast’ is valid for C/ObjC but not for C++
In file included from ../src/keypress.h:6:0,
                 from ../src/robotjs.cc:7:
../src/keycode.h:103:23: fatal error: X11/Xutil.h: No such file or directory
compilation terminated.
robotjs.target.mk:114: recipe for target 'Release/obj.target/robotjs/src/robotjs.o' failed
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
make: Leaving directory '/tmp/del/zazu-master/node_modules/robotjs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dev/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.8.0-36-generic
gyp ERR! command "/home/dev/.nvm/versions/node/v8.1.4/bin/node" "/home/dev/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/del/zazu-master/node_modules/robotjs
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN @0.5.2 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2017-07-12T06_01_21_366Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.5.2 prerelease: `npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @0.5.2 prerelease script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2017-07-12T06_01_21_570Z-debug.log
```

**Comment by bayleedev** [comment]
Use 6.5.0

https://github.com/tinytacoteam/zazu/blob/master/.nvmrc

**Comment by AnirbanKundu** [comment]
I upgraded node from brew on my Mac. And after I did that I am receiving a very similar exception.  
@blainesch - I could not understand your fix. Please could you explain

**Comment by softwarecreations** [comment]
@blainesch I'm surprised you closed the issue, is it not intended for zazu to ever support new versions of node.js?

@AnirbanKundu blainesch was referring to the version of node.js that is required for zazu.
NVM is node version manager.

**Comment by bayleedev** [comment]
@softwarecreations I don't think upgrading a language version for the sake of upgrading a language version is worth anybody's while. Especially given how easy nvm is and how well adopted it is for development. For production you don't need to worry about it.

If we needed it for a feature, that's another story but then that work will exist within that feature.
