### ISSUE TITLE
CentOS compile

### ISSUE THREAD

**Issue by dgrigonis1** [bayleeadamoss/zazu#316]
Guys, do you have any plans to release it on CentOS? I have spent last 4 hours trying to get any of the app launchers working and this was the closest. However, see below... Could you please help me out with this? Or maybe do a favour for all the poor people stuck with CentOS?

```shell
-$ npm install

> @0.5.2 postinstall /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu
> cd app && npm install

npm WARN zazu@0.5.2 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@^0.4.5 (node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @0.5.2 No license field.
```

AND:
```shell
-S sudo npm run release

...

  • async task error error=
                       Exit code: 1. Command failed: /root/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir -t deb --architecture amd64 --name zazu --force --after-install /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/temp-dir-yIpRsI/1-after-install --after-remove /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/temp-dir-yIpRsI/0-after-remove --description 
                        A cross platform productivity application. --version 0.5.2 --package /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/dist/zazu_0.5.2_amd64.deb --maintainer Tiny Taco Team <zazu-app@googlegroups.com> --url http://zazuapp.org --vendor Tiny Taco Team <zazu-app@googlegroups.com> --log debug --debug --deb-compression xz --depends gconf2 --depends gconf-service --depends libnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --depends libxss1 --license MIT /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/dist/linux-unpacked/=/opt/Zazu /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/resources/icons/512x512.png=/usr/share/icons/hicolor/512x512/apps/zazu.png /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/temp-dir-yIpRsI/2-Zazu.desktop=/usr/share/applications/zazu.desktop


...

    at /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/builder-util/src/util.ts:122:16
    at ChildProcess.exithandler (child_process.js:211:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at exec (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/builder-util/src/util.ts:85:3)
    at /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/src/targets/fpm.ts:232:11
    at next (native)
From previous event:
    at FpmTarget.build (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/out/targets/fpm.js:280:11)
    at default.each.it (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/src/platformPackager.ts:120:89)
From previous event:
    at taskManager.addTask.default.map.then (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/src/platformPackager.ts:120:37)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/src/platformPackager.ts:120:10)
    at /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/src/platformPackager.ts:114:10
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at LinuxPackager.pack (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/out/platformPackager.js:196:11)
    at /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/src/packager.ts:364:24
    at next (native)
    at xfs.stat (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/graceful-fs/polyfills.js:287:18
From previous event:
    at Packager.doBuild (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/out/packager.js:432:11)
    at /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/src/packager.ts:308:52
    at next (native)
    at /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager._build (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/out/packager.js:376:11)
    at /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/src/packager.ts:270:23
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder-lib/out/packager.js:332:11)
    at /home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder/src/builder.ts:310:40
    at next (native)
From previous event:
    at _build (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/winnt/TIBRA/dominykas.grigonis/Downloads/zazu/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

* Zazu:
* OS: CentOS 7.3
* GIT:

**Comment by afaur** [comment]
I was able to reproduce this issue using CentOS 7.3...

@dgrigonis1 Please check to see if you have some lines between the `async task...` and the ` at /home/winnt...` lines. It would be where you used the second ellipsis `...`. 

Do you see a line (the lines were in yellow) that looks similar to the warning/error that I saw? (warning/error listed below)

```
...
{:timestamp=>"2018-04-12T01:10:41.768671+0000", :message=>"tar (child): '/root/.cache/electron-builder/app-builder/app-builder-v0.6.1-x64/app-builder': Cannot exec: No such file or directory", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
{:timestamp=>"2018-04-12T01:10:41.768991+0000", :message=>"tar (child): Error is not recoverable: exiting now", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
...
```

Based on this error/warning I think this may be an issue with `app-builder`, but it is hard to say.  

@dgrigonis1 - What happens if you run `npm run start` instead of `npm run release`?

**Comment by dgrigonis1** [comment]
```
...
{:timestamp=>"2018-04-12T09:27:38.047991+0100", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn, :file=>"/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/package/deb.rb", :line=>"820", :method=>"write_conffiles"}
                       {:timestamp=>"2018-04-12T09:27:38.254160+0100", :message=>"Creating", :path=>"/tmp/package-deb-build-467afb6ab9d6afbf8a0e8825b85d2d7b10981d037faba3987b044b897847/control.tar.gz", :from=>"/tmp/package-deb-build-467afb6ab9d6afbf8a0e8825b85d2d7b10981d037faba3987b044b897847/control", :level=>:info, :file=>"/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/package/deb.rb", :line=>"728", :method=>"block in write_control_tarball"}
                       {:timestamp=>"2018-04-12T09:27:38.265825+0100", :message=>"Running command", :args=>["tar", "-C", "/tmp/package-deb-build-467afb6ab9d6afbf8a0e8825b85d2d7b10981d037faba3987b044b897847/control", "-zcf", "/tmp/package-deb-build-467afb6ab9d6afbf8a0e8825b85d2d7b10981d037faba3987b044b897847/control.tar.gz", "--owner=0", "--group=0", "--numeric-owner", "."], :level=>:debug, :file=>"/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/util.rb", :line=>"145", :method=>"execmd"}
                       {:timestamp=>"2018-04-12T09:27:38.267482+0100", :message=>"Process is running", :pid=>1426, :level=>:debug, :file=>"/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/util.rb", :line=>"163", :method=>"execmd"}
                       {:timestamp=>"2018-04-12T09:27:38.269699+0100", :message=>"Removing no longer needed control dir", :path=>"/tmp/package-deb-build-467afb6ab9d6afbf8a0e8825b85d2d7b10981d037faba3987b044b897847/control", :level=>:debug, :file=>"/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/package/deb.rb", :line=>"741", :method=>"write_control_tarball"}
                       {:timestamp=>"2018-04-12T09:27:38.270099+0100", :message=>"Running command", :args=>["tar", "-C", "/tmp/package-dir-staging-d6bd3b31abf5d1d7ee3e708fc02b1f248a1da03e0ef95ce137afe5417335", "-I'/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/app-builder/app-builder-v0.6.1-x64/app-builder'", "--numeric-owner", "--owner", "0", "--numeric-owner", "--group", "0", "-cf", "/tmp/package-deb-build-467afb6ab9d6afbf8a0e8825b85d2d7b10981d037faba3987b044b897847/data.tar.xz", "."], :level=>:debug, :file=>"/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/util.rb", :line=>"145", :method=>"execmd"}
                       {:timestamp=>"2018-04-12T09:27:38.271931+0100", :message=>"Process is running", :pid=>1430, :level=>:debug, :file=>"/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/util.rb", :line=>"163", :method=>"execmd"}
                       {:timestamp=>"2018-04-12T09:27:38.273409+0100", :message=>"tar (child): '/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/app-builder/app-builder-v0.6.1-x64/app-builder': Cannot exec: No such file or directory", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
                       {:timestamp=>"2018-04-12T09:27:38.273514+0100", :message=>"tar (child): Error is not recoverable: exiting now", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
                       {:timestamp=>"2018-04-12T09:27:38.273611+0100", :message=>"tar: /tmp/package-deb-build-467afb6ab9d6afbf8a0e8825b85d2d7b10981d037faba3987b044b897847/data.tar.xz: Wrote only 4096 of 10240 bytes", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
                       {:timestamp=>"2018-04-12T09:27:38.273688+0100", :message=>"tar: Error is not recoverable: exiting now", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
                       {:timestamp=>"2018-04-12T09:27:38.273825+0100", :message=>"Process failed: tar failed (exit code 2). Full command was:[\"tar\", \"-C\", \"/tmp/package-dir-staging-d6bd3b31abf5d1d7ee3e708fc02b1f248a1da03e0ef95ce137afe5417335\", \"-I'/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/app-builder/app-builder-v0.6.1-x64/app-builder'\", \"--numeric-owner\", \"--owner\", \"0\", \"--numeric-owner\", \"--group\", \"0\", \"-cf\", \"/tmp/package-deb-build-467afb6ab9d6afbf8a0e8825b85d2d7b10981d037faba3987b044b897847/data.tar.xz\", \".\"]", :level=>:error, :file=>"/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/command.rb", :line=>"505", :method=>"rescue in execute"}
                       {:timestamp=>"2018-04-12T09:27:38.274527+0100", :message=>"Cleaning up staging path", :path=>"/tmp/package-dir-staging-d6bd3b31abf5d1d7ee3e708fc02b1f248a1da03e0ef95ce137afe5417335", :level=>:debug, :file=>"/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/package.rb", :line=>"284", :method=>"cleanup_staging"}
                       {:timestamp=>"2018-04-12T09:27:38.281490+0100", :message=>"Cleaning up build path", :path=>"/tmp/package-dir-build-df6c0e17ceb4dfd61a8375fa5c2753b91baad6e42b0eaf55d9d2bf8513d8", :level=>:debug, :file=>"/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/package.rb", :line=>"291", :method=>"cleanup_build"}
                       {:timestamp=>"2018-04-12T09:27:38.281630+0100", :message=>"Cleaning up build path", :path=>"/tmp/package-deb-build-467afb6ab9d6afbf8a0e8825b85d2d7b10981d037faba3987b044b897847", :level=>:debug, :file=>"/home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/package.rb", :line=>"291", :method=>"cleanup_build"}
                       
Error: Exit code: 1. Command failed: /home/winnt/TIBRA/dominykas.grigonis/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir -t deb --architecture amd64 --name zazu --force --after-install /tmp/temp-dir-IWrXEQ/0-after-install --after-remove /tmp/temp-dir-IWrXEQ/1-after-remove --description 
 A cross platform productivity application. --version 0.5.2 --package /home/winnt/TIBRA/dominykas.grigonis/zazu/dist/zazu_0.5.2_amd64.deb --maintainer Tiny Taco Team <zazu-app@googlegroups.com> --url http://zazuapp.org --vendor Tiny Taco Team <zazu-app@googlegroups.com> --log debug --debug --deb-compression xz --depends gconf2 --depends gconf-service --depends libnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --depends libxss1 --license MIT /home/winnt/TIBRA/dominykas.grigonis/zazu/dist/linux-unpacked/=/opt/Zazu /home/winnt/TIBRA/dominykas.grigonis/zazu/resources/icons/512x512.png=/usr/share/icons/hicolor/512x512/apps/zazu.png /tmp/temp-dir-IWrXEQ/2-Zazu.desktop=/usr/share/applications/zazu.desktop
...
```

**Comment by dgrigonis1** [comment]
`npm run start`

results in frozen state:

```
$ sudo npm run start

> @0.5.2 start /home/winnt/TIBRA/dominykas.grigonis/zazu
> cross-env NODE_ENV=development electron ./app

npm WARN lifecycle The node binary used for scripts is /home/winnt/TIBRA/dominykas.grigonis/zazu/node_modules/.bin/electron but npm is using /home/winnt/TIBRA/dominykas.grigonis/zazu/node_modules/electron/dist/electron itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
npm WARN zazu-package-manager@1.0.0 No repository field.
npm WARN zazu-file-finder@1.0.0 No repository field.
npm WARN zazu-system@0.0.1 No license field.
[            ......] | postinstall: WARN zazu-system@0.0.1 No license field.
```
