### ISSUE TITLE
Fedora Cinnamon Error Compiling

### ISSUE THREAD

**Issue by MadeByL9** [bayleeadamoss/zazu#321]
Error when compiling zazu

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.8.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-05T02_46_49_540Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.5.2 prerelease: `npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @0.5.2 prerelease script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-05T02_46_49_706Z-debug.log

debug log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'release' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle @0.5.2~prerelease: @0.5.2
6 verbose lifecycle @0.5.2~prerelease: unsafe-perm in lifecycle true
7 verbose lifecycle @0.5.2~prerelease: PATH: /usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/node-gyp-bin:/home/fedora/zazu/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
8 verbose lifecycle @0.5.2~prerelease: CWD: /home/fedora/zazu
9 silly lifecycle @0.5.2~prerelease: Args: [ '-c', 'npm install' ]
10 silly lifecycle @0.5.2~prerelease: Returned: code: 1  signal: null
11 info lifecycle @0.5.2~prerelease: Failed to exec prerelease script
12 verbose stack Error: @0.5.2 prerelease: `npm install`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/index.js:285:16)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at EventEmitter.emit (events.js:214:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid @0.5.2
14 verbose cwd /home/fedora/zazu
15 verbose Linux 4.16.13-300.fc28.x86_64
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "release"
17 verbose node v8.11.2
18 verbose npm  v5.6.0
19 error code ELIFECYCLE
20 error errno 1
21 error @0.5.2 prerelease: `npm install`
21 error Exit status 1
22 error Failed at the @0.5.2 prerelease script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by bayleedev** [comment]
Thank you for reporting it!
