### ISSUE TITLE
Large plugin load before download finished

### ISSUE THREAD

**Issue by linonetwo** [bayleeadamoss/zazu#337]
My plugin contains a 1MB binary file, I found that following error thrown before files occurred in the `~/.zazu/plugins/linonetwo/zazu-firefox-bookmarks`, maybe code executes before file fully downloaded:

```
Error: Cannot find module '/Users/linonetwo/.zazu/plugins/linonetwo/zazu-firefox-bookmarks/zazu.json'\n    at Module._resolveFilename (module.js:455:15)\n    at Function.Module._resolveFilename (/Applications/Zazu.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12
```

https://github.com/tinytacoteam/zazu/blob/363d517e4709fe4bff220b8b2890d7ca84fa0d5e/app/packages/package.js#L22-L32

```
TypeError: Cannot read property 'stylesheet' of undefined
at /Applications/Zazu.app/Contents/Resources/app.asar/packages/plugin.js:74:11
```

https://github.com/tinytacoteam/zazu/blob/363d517e4709fe4bff220b8b2890d7ca84fa0d5e/app/packages/plugin.js#L75-L77

Though errors are thrown, my plugin still works.

**Comment by linonetwo** [comment]
Fixed in https://github.com/tinytacoteam/zazu/pull/341
