### ISSUE TITLE
Cannot install sqlite

### ISSUE THREAD

**Issue by linonetwo** [bayleeadamoss/zazu#339]
### Expected Behavior

Install and node-gyp rebuild

### Actual Behavior

```
{ Error: sqlite3@4.0.8 install: `node-pre-gyp install --fallback-to-build`
spawn ENOENT
    at ChildProcess.<anonymous> (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/npm/lib/utils/spawn.js:33:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  code: 'ELIFECYCLE',
  errno: 'ENOENT',
  syscall: 'spawn',
  file: 'sh',
  pkgid: 'sqlite3@4.0.8',
  stage: 'install',
  script: 'node-pre-gyp install --fallback-to-build',
  pkgname: 'sqlite3',
  parent: 'zazu-firefox-bookmarks' }
```

### Steps to reproduce the behavior

A simple plugin with require('sqlite')

### Versions

App Environment: production
App Version: 0.5.2
Electron Version: 1.3.14
Node Version: 6.5.0
Chrome Version: 52.0.2743.82

**Comment by linonetwo** [comment]
use sql.js instead, it uses wasm and only requires node version > 10
