### ISSUE TITLE
Plugin errors

### ISSUE THREAD

**Issue by julienfantin** [bayleeadamoss/zazu#90]
Running on osx 10.11.6 only the system module seemed to work for me.

Apologies for bundling these together but they all seem related to some dependencies issue? I tried both the package as well as building from source

Here are some excerpts from the log file:

```
{"message":"Plugin failed to load","stack":["Error: Cannot find module 'typed-function'","    at Module._resolveFilename (module.js:455:15)","    at Function.Module._resolveFilename (/Applications/Zazu.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)","    at Function.Module._load (module.js:403:25)","    at Module.require (module.js:483:17)","    at require (internal/module.js:20:19)","    at Object.<anonymous> (/Users/julien/.zazu/plugins/tinytacoteam/zazu-calculator/node_modules/mathjs/lib/core/typed.js:1:100)","    at Module._compile (module.js:556:32)","    at Object.Module._extensions..js (module.js:565:10)","    at Module.load (module.js:473:32)","    at tryModuleLoad (module.js:432:12)"],"plugin":"tinytacoteam/zazu-calculator","block":"Service","level":"error"}
```
```
{"message":"Plugin failed to load","stack":["Error: Cannot find module 'clone'","    at Module._resolveFilename (module.js:455:15)","    at Function.Module._resolveFilename (/Applications/Zazu.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)","    at Function.Module._load (module.js:403:25)","    at Module.require (module.js:483:17)","    at require (internal/module.js:20:19)","    at Object.<anonymous> (/Users/julien/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/color/index.js:2:13)","    at Module._compile (module.js:556:32)","    at Object.Module._extensions..js (module.js:565:10)","    at Module.load (module.js:473:32)","    at tryModuleLoad (module.js:432:12)"],"plugin":"tinytacoteam/zazu-clipboard","block":"searcher","level":"error"}
```

```
{"plugin":"tinytacoteam/zazu-file-finder","block":"FindApp","level":"error","message":"results must be an array"}
```

```
{"message":"Plugin failed to load","stack":["Error: ENOENT: no such file or directory, open '/Users/julien/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/underscore/underscore.js'","    at Error (native)","    at Object.fs.openSync (fs.js:640:18)","    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)","    at Object.fs.readFileSync (fs.js:508:33)","    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)","    at Object.Module._extensions..js (module.js:564:20)","    at Module.load (module.js:473:32)","    at tryModuleLoad (module.js:432:12)","    at Function.Module._load (module.js:424:3)","    at Module.require (module.js:483:17)"],"plugin":"tinytacoteam/zazu-clipboard","block":"Database","level":"error","timestamp":"2017-01-04T03:22:18.657Z"}
```

**Comment by bayleedev** [comment]
It looks like the plugin wasn't fully installed. I just released `v0.2.2` it might be useful to delete your `~/.zazu` directory and try this new version to see if this fixes it.

**Comment by julienfantin** [comment]
Removing `~/.zazu` helped, calculator and apps now work! However, I only see a stock icon and the zazu helper processes have been grinding at full speed for quite a while now. Are there any plans to use spotlight for file search on osx?

**Comment by bayleedev** [comment]
The file finder plugin will always aim to be cross platform since it's the default plugin that comes with it. I could see a mac specific plugin that did that though, and that might be a good first plugin! :D

I'm glad it helped!
